const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const context={window:{}};
vm.runInNewContext(fs.readFileSync('static/disk-history.js','utf8'),context);
const {prepare,allocation}=context.window.DiskHistory;
const TiB=1024**4;
const first={finished_at:100,state:'complete',roots:['/data'],users:{a:{name:'alice',bytes:2*TiB,roots:{'/data':2*TiB}},b:{name:'bob',bytes:TiB,roots:{'/data':TiB}}}};
const second={finished_at:200,state:'complete',roots:['/data'],users:{a:{name:'alice',bytes:3*TiB,roots:{'/data':3*TiB}}}};
const result=prepare([second,first],{start:50,end:250});
assert.equal(result.unit,'TiB');
assert.equal(result.scale,TiB);
assert.equal(result.totals[0],3*TiB);
assert.equal(result.rows.find(r=>r.uid==='b').values[1],0);
assert.equal(result.sampleCount,2);
assert.equal(prepare([first,second],{start:150,end:200}).sampleCount,1);
assert.equal(prepare([first,second],{start:201,end:300}).sampleCount,0);
assert.equal(prepare([first,second],{start:0,end:300,root:'/unscanned'}).sampleCount,0);
assert.equal(allocation({...second,state:'partial'},'b','all'),null);
assert.equal(allocation({...second,errors:1},'b','/data'),null);
assert.equal(allocation(second,'a','/unscanned'),null);
assert.equal(allocation(second,'b','/data'),0);
const filtered=prepare([first,second],{start:0,end:300,user:'b'});
assert.equal(filtered.rows.length,1);
assert.equal(filtered.rows[0].name,'bob');
const small={...first,users:{a:{name:'alice',bytes:512*1024**2,roots:{'/data':512*1024**2}}}};
assert.equal(prepare([small],{start:0,end:200}).unit,'MiB');
assert.equal(prepare([first,{...second,state:'partial'}],{start:0,end:300}).partial,true);
assert.equal(prepare([],{start:0,end:300}).rows.length,0);
console.log('Passed: units, time bounds, single/multiple scans, missing coverage, partial records, user selection and no fabricated zeros.');
